# Generated by Django 4.2.6 on 2023-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='duration',
            field=models.DurationField(),
        ),
    ]
