# Generated by Django 4.2.6 on 2023-11-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='mode_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='upload_by',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documentUrl',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='embedlecture',
            old_name='upload_by',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='embedlecture',
            old_name='lectureUrl',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='upload_by',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='pdfFile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='upload_by',
            new_name='instructor',
        ),
    ]
